# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: An t-Ubhal-ghort
email: chris@macmhicheil.scot
description: > # this means to ignore newlines until "baseurl:"
  Apple, teicneòlas is stuthan eile bho Chrìstean MacMhìcheil


#baseurl: "/antubhalghort" # the subpath of your site, e.g. /blog
url: "https://angeidheal.github.io" # the base hostname & protocol for your site

#footer
built-by: Crìstean MacMhìcheil

copyright:
   name: Crìstean MacMhìcheil
   link: 'https://macmhicheil.scot'

# Build settings
markdown: kramdown
permalink: /:year-:month-:day-:title/
paginate: 12
paginate_path: /duilleag-:num/

# Tracker
analytics:

# Comments
disqus: no
disqus-shortname:

#social
mastodon: https://www.mastodon.scot/@angeidheal
twitter:
instagram:
facebook:
github: https://github.com/angeidheal
email: chris@macmhicheil.scot

# Sass style
sass:
  style: compressed

# Ruby Gems
plugins:
  - jekyll-paginate
  - jekyll-seo-tag

months:
    - Am Faoilleach
    - An Gearran
    - Am Màrt
    - An Giblean
    - An Cèitean
    - An t-Ògmhios
    - An t-Iuchar
    - An Lùnastal
    - An t-Sultain
    - An Dàmhair
    - An t-Samhain
    - An Dùbhlachd
